[theme]
primaryColor = "#c1820eff"              # Laranja (botões, sliders, seletores)
backgroundColor = "#063ae6ff"        
secondaryBackgroundColor = "#95a995ff" # Laranja médio (caixas internas, cards)
textColor = "#ffffffff"                 # Texto preto para contraste
font = "sans serif"